---
# Per environment values which override defaults in hmpps-electronic-monitoring-data-insights-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: electronic-monitoring-data-insights-ui-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://electronic-monitoring-data-insights-ui-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    EMDI_API_URL: 'https://electronic-monitoring-data-insights-api-dev.hmpps.service.justice.gov.uk'
    ENVIRONMENT_NAME: DEV
    AUDIT_ENABLED: "false"
    COMPONENT_API_URL: "https://probation-frontend-components-dev.hmpps.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: hmpps-electronic-monitoring-data-insights-dev
